version: "3.9"
services:
  zookeeper:
    image: wurstmister/zookeeper
    container_name: zookeeper-local
    hostname: zookeeper-hostname
    deploy:
      mode:global
    ports:
      - "2181:2181"
    networks:
      - dev_network
  kafka:
    image: wrustmeister/kafka
    container_name: kafka-local
    hostname: kafka-hostname
    deploy:
      mode: global
    depends_on:
      - zookeeper
    command: sh -c "
      echo start_wait_for_kafka &&
      sleep 30 &&
      echo kafka_starting &&
      start-kafka.sh
    ports:
      - :9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-local:2181
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER:
        "INTERNAL://kafka-local:9090,\
          EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENER:
        "INTERNAL://kafka-local:9090,\
          EXTERNAL://localhost::9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP:
        "INTERNAL:PLAINTEXT,\
          EXTERNAL:PLAINTEST"
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_MESSAGE_MAX_BYTES: 6000000
      KAFKA_ADVERTISED_HOSTNAME: localhost
    network:
      - dev_network
     
networks:
  dev_network:
    name: local-net
    driver: bridge
    
      
      
     
    
  
    
